### ISSUE TITLE
issue using config files

### ISSUE THREAD

**Issue by SinRas** [SharifAIChallenge/AIC20-Server#3]
i use the following command to run server and also run 4 instances of client (python) to test running a game.
```bash
java -jar server.jar --extra:400
```
which works completely alright.

**according to the java source code of server**
To test faster, I want to use a config file (named `test_file.json`) as follow (which I believe are default configuration parameters):
```json
{
        "Map": "../maps/1_v1.1.2.map",
        "TeamName0": "Team0",
        "TeamName1": "Team1",
        "TeamName2": "Team2",
        "TeamName3": "Team3",
        "Deploy": "false",
        "ClientsPort": "7099",
        "ClientsConnectionTimeout": "2147483647",
        "UIEnable": "false",
        "UIToken": "00000000000000000000000000000000",
        "UIPort": "7000",
        "UIConnectionTimeout": "2147483647",
        "OCSendToUI": "false",
        "OCSendToFile": "false",
        "OCFilePath": "./game.log"
}
```
and use to following code to run the server:
```bash
java -jar server.jar --config=./test_file.json --extra=400
```
(again, the structure and order of arguments in command line is inferred from the source code and not mentioned in the docs)

The problem is that it gets stuck when I connect 4 clients. If I try to add more clients (run 5 clients), it produces the following parse error:
```bash
Info (JsonSocket): Parse error.
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at ir.sharif.aichallenge.server.common.network.JsonSocket.get(JsonSocket.java:165)
	at ir.sharif.aichallenge.server.engine.network.ClientHandler.receive(ClientHandler.java:289)
	at ir.sharif.aichallenge.server.engine.network.ClientHandler.lambda$getReceiver$1(ClientHandler.java:244)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 12 more
```

**Comment by taslimisina** [comment]
If you just want to set default map it's possible to do so by creating and setting a system environment variable named "AICMap" and set it's value to be the path to the map file.

**Comment by taslimisina** [comment]
The problem you mentioned was a problem in network that was fixed now. I will close the issue. If the problem still occurs, feel free to re-open it and tell us.
